-- Idempotent schema migration for the trades app.
-- Safe to re-run: adds only what is missing and replaces policies in place.
--
-- Two bugs in an earlier version of this file stopped it from ever applying,
-- which is why the live database drifted from it:
--   1. "create policy if not exists" is not valid PostgreSQL -- CREATE POLICY
--      has no IF NOT EXISTS clause, so the script aborted at that statement.
--   2. INSERT policies take WITH CHECK, not USING.
--
-- A third drift was found later and is fixed below: this file described a
-- `moods.mood` column, but the app has always written `mood_tag` plus a
-- `motion_flag` (the accelerometer sample taken while logging the mood), and
-- it reads and writes `trades.profit_loss`, which this file never created.
-- Re-running the old version would have added a NOT NULL `mood` column and
-- broken every insert.

-- ---------------------------------------------------------------------------
-- trades
-- ---------------------------------------------------------------------------
-- NOTE: the live table already uses a bigint identity id (not uuid), so this
-- only creates the table when it is genuinely absent and never retypes it.
create table if not exists public.trades (
  id bigint generated by default as identity primary key,
  pair text not null,
  direction text not null,
  entry_price numeric not null,
  exit_price numeric not null,
  size numeric not null,
  setup_type text not null,
  notes text,
  profit_loss numeric,
  created_at timestamptz not null default now()
);

alter table public.trades add column if not exists pair        text;
alter table public.trades add column if not exists direction   text;
alter table public.trades add column if not exists entry_price numeric;
alter table public.trades add column if not exists exit_price  numeric;
alter table public.trades add column if not exists size        numeric;
alter table public.trades add column if not exists setup_type  text;
alter table public.trades add column if not exists notes       text;
-- Nullable on purpose: rows predating the Add Trade form's stored-P/L change
-- have no value, and the app derives P/L from the price columns for those.
alter table public.trades add column if not exists profit_loss numeric;
alter table public.trades add column if not exists created_at  timestamptz not null default now();

-- ---------------------------------------------------------------------------
-- moods
-- ---------------------------------------------------------------------------
-- One trade can carry several mood rows, joined on trade_id.
create table if not exists public.moods (
  id bigint generated by default as identity primary key,
  trade_id bigint not null references public.trades (id) on delete cascade,
  mood_tag text not null,
  motion_flag text,
  created_at timestamptz not null default now()
);

alter table public.moods add column if not exists mood_tag    text;
-- Null on web, where there is no accelerometer to sample.
alter table public.moods add column if not exists motion_flag text;
alter table public.moods add column if not exists created_at  timestamptz not null default now();

-- Drop the constraint from the pre-`mood_tag` version of this file, so a
-- database that did apply it is not left checking a column the app never writes.
alter table public.moods drop constraint if exists moods_mood_check;

-- Constrain mood_tag to the five values the picker in
-- src/components/add-trade-sheet.tsx sends.
alter table public.moods drop constraint if exists moods_mood_tag_check;
alter table public.moods
  add constraint moods_mood_tag_check
  check (mood_tag in ('calm', 'anxious', 'confident', 'frustrated', 'impatient'));

-- motion_flag is written by src/lib/motion-sensor.ts, which reports one of two
-- readings or nothing at all when no sensor is available.
alter table public.moods drop constraint if exists moods_motion_flag_check;
alter table public.moods
  add constraint moods_motion_flag_check
  check (motion_flag is null or motion_flag in ('steady', 'restless'));

-- The trades table and calendar both filter moods by trade_id on every load.
create index if not exists moods_trade_id_idx on public.moods (trade_id);

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------
-- WARNING: these policies let any anonymous caller read and insert every row.
-- That is fine for a single-user development database and NOT fine once this
-- app is shown to anyone else -- scope them to auth.uid() before then.
alter table public.trades enable row level security;
alter table public.moods  enable row level security;

-- Drop-then-create is the idempotent pattern, since CREATE POLICY has no
-- IF NOT EXISTS. INSERT policies require WITH CHECK; SELECT requires USING.
drop policy if exists "Allow reads for all users"   on public.trades;
drop policy if exists "Allow inserts for all users" on public.trades;

create policy "Allow reads for all users" on public.trades
  for select to anon, authenticated using (true);

create policy "Allow inserts for all users" on public.trades
  for insert to anon, authenticated with check (true);

drop policy if exists "Allow reads for all users"   on public.moods;
drop policy if exists "Allow inserts for all users" on public.moods;

create policy "Allow reads for all users" on public.moods
  for select to anon, authenticated using (true);

create policy "Allow inserts for all users" on public.moods
  for insert to anon, authenticated with check (true);

-- Ask PostgREST to refresh its schema cache so the new columns are visible
-- immediately rather than after the next automatic reload.
notify pgrst, 'reload schema';
